### ISSUE TITLE
Casper 皮肤文章内容标题目录锚点定位跳转被标题工具栏覆盖

### ISSUE THREAD

**Issue by iTanken** [b3log/solo-skins#29]
`Casper` 皮肤点击目录跳转到对应位置后，标题 `一、简介` 被顶部工具栏覆盖，如下图：
> ![image](https://user-images.githubusercontent.com/23544702/56351109-ec90a280-61fe-11e9-9155-5bbad3287522.png)

有一种解决方式是：
```css
h1:target, h2:target, h3:target, h4:target, h5:target, h6:target {
  padding-top: 70px;
}
```
